import { FC, ReactNode } from "react"

interface LayoutProps {
    children: ReactNode
}

export const metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
  }

const Layout: FC<LayoutProps> = ({ children }) => {
    return <div className=''>{children}</div>
}

export default Layout